@ECHO OFF
SET TESTRESULT=1
ECHO:
SET STARTINGDIR=%CD%
CD %~dp0\..\WOOD0350v2\
ECHO Translating Adventure from Fortran to C...
%~dp0\..\fortran\x64\Debug\fortran ADVENT.for
SET TESTRESULT=%ERRORLEVEL%
IF %TESTRESULT% NEQ 0 GOTO DONE
ECHO:
ECHO Compiling ADVENT.c...
REM Debug version
cl /nologo /std:c11 /W4 /Od /ZI /Fo:target\ADVENT.obj /Fe:target\ADVENT.exe target\ADVENT.c
REM Release version
REM cl /std:c11 /W4 /O2 /DNDEBUG /GF /ZI /Fo:target\ADVENT.obj /Fe:target\ADVENT.exe target\ADVENT.c
SET TESTRESULT=%ERRORLEVEL%
IF %TESTRESULT% NEQ 0 GOTO DONE
ECHO:
ECHO Executing ADVENT.exe...
target\ADVENT.exe
SET TESTRESULT=%ERRORLEVEL%
:DONE
CD /D %STARTINGDIR%
ECHO:
IF %TESTRESULT% NEQ 0 ECHO Failed (exit code was %TESTRESULT%)
IF %TESTRESULT% EQU 0 ECHO SUCCESS!
ECHO ON
@EXIT /B %TESTRESULT%
