#include "parser.h"
//#include "generator.h"
#include "cgenerator.h"
#include "utility.h"

#include <array>
#include <cstdlib>
#include <filesystem>
#include <format>
#include <fstream>
#include <iostream>
#include <print>
#include <vector>

void save_symbol_table(
    aid::fortran::program const &program,
    std::filesystem::path const &directory
) {
    auto const sym_file_path =
        (directory / program.name().view()).replace_extension(".sym");
    auto fsymtab = std::ofstream(sym_file_path);
    if (!fsymtab) {
        std::print(std::cerr, "could not save symbol table to \"{}\"\n",
                   sym_file_path.string());
        return;
    }

    for (auto const &sub : program) {
        sub.print_symbol_table(fsymtab);
    }
}

void translate_to_c(
    aid::fortran::program const &program,
    std::filesystem::path const &directory
) {
    auto const c_file_name =
        (directory / program.name().view()).replace_extension(".c");
    auto fcode = std::ofstream(c_file_name);
    if (!fcode) {
        std::print(std::cerr, "could not save C translation to \"{}\"\n",
                   c_file_name.string());
        return;
    }
    std::print(fcode,
R"(// This file was generated by a Fortran-to-C translator.
// Learn more at https://github.com/aidtopia/fortran-adventure
)");

    auto const &sources = program.get_source_files();
    if (!sources.empty()) {
        std::print(fcode, "//  Source{}:\n", sources.size() != 1 ? "s" : "");
        for (auto const &path : sources) {
            std::print(fcode, "//    {}\n", path.string());
        }
    }

    std::print(fcode, "{}", aid::fortran::c_generator::generate_c(program));
}

void show_usage(std::ostream &out) {
    std::print(out, "Usage: fortran <file>...\n");
}

int main(int argc, char const *argv[]) {
    if (argc < 2) {
        show_usage(std::cerr);
        return EXIT_FAILURE;
    }

    // Resolve the source file names.
    auto constexpr extensions = std::array<std::string_view, 5>{
        ".f", ".for", ".f4", ".fiv", ".fortran"
    };
    auto paths = std::vector<std::filesystem::path>{};
    for (int i = 1; i < argc; ++i) {
        if (argv[i][0] == '@') {
            // `@foo.txt` means read file names from foo.txt
            if (auto indirect = std::ifstream{argv[i]+1}; indirect) {
                auto line = std::string{};
                while (std::getline(indirect, line)) {
                    paths.push_back(aid::resolve_filename(line, extensions));
                }
            }
        } else {
            paths.push_back(aid::resolve_filename(argv[i], extensions));
        }
    }

    // FRONT END ---------------

    // Parse the code.
    auto parsed = aid::fortran::parser::parse_files(paths);
    if (!parsed.has_value()) {
        std::print(std::cerr, "{}\n", parsed.error().message());
        return EXIT_FAILURE;
    }
    auto program = std::move(parsed).value();


    // MIDDLE END --------------
    // Here we do "passes" over `program`, shaping it as needed.

    // Determine what code is reachable and what symbols are referenced by
    // marking the program as reachable and letting recursion do the work.
    mark_reachable(program);

    // Assign addresses to all of the (referenced) variables that will need
    // space in the program's memory.
    assign_addresses(program);

    // BACK END ----------------

    // Create the target directory beneath the directory that contains the first
    // source file.
    auto const cwd = std::filesystem::current_path();
    auto const first = paths.front();
    auto const base = (first.is_relative() ? cwd/first : first).parent_path();
    auto const directory = (base/"target").lexically_normal();
    auto ec = std::error_code{};
    if (!std::filesystem::create_directory(directory, ec) && ec) {
        std::print(std::cerr, "Failed to create target directory \"{}\".\n{}\n",
                   directory.string(), ec.message());
        return ec.value();
    }

    save_symbol_table(program, directory);

    translate_to_c(program, directory);

    return 0;
}
